# Generated by Django 4.0.5 on 2022-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
